version: "0.1"

services:
  web-nestjs:
    build:
      context: "../."
      dockerfile: Docker/Dockerfile
    container_name: test-container-compose
    image: test-image
    restart: always
    ports:
      - "3400:3000"
    links:
      - bd-mysql
    depends_on:
      - bd-mysql
    networks:
      test_net:
          ipv4_address: 172.22.0.7

  bd-mysql:
    container_name: mysql-compose
    image: mysql:5.7.37
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: aluxion-test
    networks:
      test_net:
        ipv4_address: 172.22.0.5

networks:
  test_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/24